### ISSUE TITLE
Windows build not working

### ISSUE THREAD

**Issue by brewsoftware** [prescottprue/generator-react-firebase#1]
When running the build commands, "cp" doesn't exist on windows. I would suggest just piping the assets using a plugin or another command specific to npm.

**Comment by prescottprue** [comment]
Didn't even consider this initially, thanks for the input!

Planning on implementing an NPM package to do this in a more graceful way.

**Comment by prescottprue** [comment]
Pull Request #2 should have fixed it since it is now using [fs-extra](https://github.com/jprichardson/node-fs-extra).

Planning on releasing a new version tomorrow. I will leave this open until it is in a released version even though this PR has been merged.

**Comment by brewsoftware** [comment]
No problem, nice generator though so compliments to the chef...

**Comment by prescottprue** [comment]
Version v0.1.1 has been released with this fix in there, let me know if that does not fix it. Thanks for the help identifying it.
