### ISSUE TITLE
Missing material-ui on a new install

### ISSUE THREAD

**Issue by dzoba** [prescottprue/generator-react-firebase#103]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Though I selected material-ui as an option, I still got:
![image](https://user-images.githubusercontent.com/857664/41138610-4cd000a6-6a97-11e8-8677-703dd34c1b7a.png)

**What is the expected behavior?**
material-ui is in package.json when option is selected

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Latest version

**Comment by prescottprue** [comment]
If you picked the default options in generator then both `@material-ui/core` and `@material-ui/icons` are installed by default (the [new pattern for material ui v1](material-ui.com)). If you have a project with existing material-ui code that is from before the v1 release, you can opt out of material-ui v1 (in feature options) - this will install `material-ui` with version `v0.20.0`.
