### ISSUE TITLE
feat(component): component templates aware of dependencies and lint config

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/generator-react-firebase#105]
**Do you want to request a *feature* or report a *bug*?**  
feature

**What is the current behavior?**
When calling `yo react-firebase:component` a component is inserted. The templates for this component use `js-standard` lint config. The linting

**What is the expected behavior?**
* component code matches linting style (i.e. support Airbnb style linting)
* `PropTypes` is loaded from `react` if `prop-types` does not exist in `package.json`

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

**Comment by petermiles** [comment]
I'll pick this up.
