### ISSUE TITLE
Firebase app named

### ISSUE THREAD

**Issue by brunowego** [prescottprue/generator-react-firebase#11]
I catch a warning message:

```
Firebase error: Error: Firebase App named '[DEFAULT]' already exists.(…)
```

Do you know how fix it?

**Comment by prescottprue** [comment]
This is due to the internals of [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3) calling `firebase.initializeApp()` more than once. Currently working to fix it within that library, but it should not cause any issues.

**Comment by prescottprue** [comment]
Will leave this issue open until it is solved in [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3)

**Comment by brunowego** [comment]
Alright, thanks for the quick reply!

**Comment by prescottprue** [comment]
It is solved in https://github.com/prescottprue/redux-firebasev3/releases/tag/v0.1.0, which is in the latest 0.1.5 release of this generator.
