### ISSUE TITLE
Endless loading after signin

### ISSUE THREAD

**Issue by Edw1nLee** [prescottprue/generator-react-firebase#112]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
continue loading after login with a new instance

**What is the expected behavior?**
user able to check account page or project page as same as material example

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Chrome. macos
the material example works fine.

**Comment by prescottprue** [comment]
@Edw1nLee Did you end up figuring out what the issue was? Is there something that could be added to the docs to make it more clear?
