### ISSUE TITLE
Getting userAdditionalInfo

### ISSUE THREAD

**Issue by muzajoji** [prescottprue/generator-react-firebase#119]
I am looking to add a component to be displayed when logging in for the first time. How can I use the userAdditionalInfo mentioned here? 

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AdditionalUserInfo

**Comment by prescottprue** [comment]
The provided link seems to point to Firebase's Android SDK Reference, where generator outputs a web app.

That said, creating a component that is shown when the user is first logged in is as easy as just storing a parameter on the user's profile.
