### ISSUE TITLE
Form generator uses old material-ui/Button import

### ISSUE THREAD

**Issue by dustingraves** [prescottprue/generator-react-firebase#122]
**Describe the bug**
When generating a new form it uses the old Button import instead of the v1.x `@material-ui/core`

**To Reproduce**
1. run `yo react-firebase:form newForm`
2. go to new component and look at `components/newForm/newForm.js`
4. Error is on line 5

```js
import React from 'react'
import PropTypes from 'prop-types'
import { Field } from 'redux-form'
import { TextField } from 'redux-form-material-ui'
import Button from 'material-ui/Button'
import classes from './NewForm.scss'

```

**Expected behavior/code**
The form generator should use the new `@material-ui/core` package

```js
import Button from '@material-ui/core/Button'
```

**Environment**
- generator-react-firebase version: 2.1.1
- Material UI version: 3.1.0
- Babel version(s): core 6.24.1 / loader 7.0.0
- Node/npm version: Node 10/npm 6.4.1
- OS: OS X 10.13.5
- Monorepo no
- How you are using Babel: loader (default)

**Possible Solution**
check to see if `theme.js` exists and assume `materialv1` or have it read from a config file in the project.

**Comment by prescottprue** [comment]
Fixed in [v2.2.0 release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.2.0). Thanks for reporting!
