### ISSUE TITLE
Sign-up not working

### ISSUE THREAD

**Issue by brunowego** [prescottprue/generator-react-firebase#13]
Both methods of sign-up not works correctly. I get the message below. You know how fix?

```
Signup.js?a67e:68 error signing up: Q {code: "auth/argument-error", message: "signInWithEmailAndPassword failed: First argument "email" must be a valid string."} Error: signInWithEmailAndPassword failed: First argument "email" must be a valid string.
```

**Comment by brunowego** [comment]
Have been enabled "E-mail/senha" and "Google" authentications methods in Firebase.

**Comment by prescottprue** [comment]
Created an issue in ZenHub (trying it out for issue/task management) for this. Will hopefully be looking at it later today.

Can you post the options you selected (mostly whether you opted for redux or not) so I can better debug?

**Comment by brunowego** [comment]
Yes, I selected the option with redux.

**Comment by prescottprue** [comment]
#15 And the new release should have fixed the auth stuff. Let me know if you have an issue still.

**Comment by prescottprue** [comment]
Since there has been no response I am assuming everything is working for you now @brunowego. Going to close this issue, but feel free to keep the conversation going or contact me directly if it didn't fix it for you. Thanks for the help in catching it!

**Comment by Barath-prakash** [comment]
O {code: "auth/argument-error", message: "signInWithEmailAndPassword failed: First argument "email" must be a valid string."}
how fix this problem?? please help me

**Comment by Barath-prakash** [comment]
@prescottprue

**Comment by Barath-prakash** [comment]
my code is here,
weddsApp.controller('loginCtrl', ['$scope','jwtTokenValue','$ionicPopup','$firebaseAuth',
                           function ($scope, jwtTokenValue, $ionicPopup,$firebaseAuth) {
	   
	  $scope.userLogin = function(email, password){
		  console.log(email);
		  console.log(password);
		  firebase.auth().signInWithEmailAndPassword(email, password).then(function(data) {
			   console.log(data);
			});
		  
		};

	  }]);

**Comment by prescottprue** [comment]
@Barath-prakash I don't believe what you are seeing is related to this issue.

1. It is difficult to understand where an issue may be coming from without a full reproduction of the error.
2. Not sure where you are getting `firebase` from in that snippet
3. Using the Firebase instance separately will not yield what you are expecting in redux state

Please open a new issue with more details including a whole reproduction

**Comment by Barath-prakash** [comment]
Please open a new issue with more details including a whole reproduction
Okay... i will
