### ISSUE TITLE
Application Structure - actions

### ISSUE THREAD

**Issue by MincePie** [prescottprue/generator-react-firebase#130]
**Describe the bug**
I am trying to setup a version of this base to use the material-ui example. The application structure within that example has an index.js page, that uses the following import statement: import constants, { actionTypes } from './constants'

I'm not familiar with this syntax to see exactly how it works, but I think it needs the actions folders that is in the src folder at root level (not duplicated in the src folder at material subfolder example level) to run this statement. If that's the case, do I also need to bring all of the root level src folder items across?

If the intention is to combine the content of the root level source folder with the src in the material-ui example, is it intended that the content of the two constants.js files should be merged? Please could you provide some help in how that should be achieved.
**To Reproduce**
Follow the getting started instructions and then compare the application structure readme to the code. There is more in the code than in the readme.

**Expected behavior/code**
A complete setup of the material ui example.

**Babel Configuration (.babelrc, package.json, cli command)**

I have config folder at root level with the 3 files in it as well as a root level project.config.js.

**Environment**

**Possible Solution**
Please could you expand the readme so I can get the application structure right before I try to start figuring out how to use it. 

**Additional context/Screenshots**
Thank you

**Comment by prescottprue** [comment]
The syntax that you are asking about allows for the default import as well as a non default import in one statement:

```js
```

This is really common in the react community for pulling in `react` as well as `React.Component` like so:

```js
import react, { Component } from 'react'
```

As for the difference in the README and the structure you see in the example, I will work on cleaning that up.The examples are generally updated, but since there are a number of options while installing, that means many examples have to be updated. What I usually tell folks is that the best way to see what comes out of the generator is to actually try running it with a bogus project name like "basic". Then, if you end up not liking the tool, you can simple uninstall just as easily with `npm uninstall -g generator-react-firebase`.

Thanks for reaching out!

**Comment by MincePie** [comment]
Thanks very much @prescottprue - it all looks clean and neat, I'm just suck trying to figure out if I like it. I'm trying to compile a single set of files to get a version of the code to start (still stuck in trying to do that). I'll keep trying and share any notes that might be helpful for the next draft of the readme. Thanks again!

**Comment by prescottprue** [comment]
Yup! This generator is mostly setup to scale to large applications based on patterns myself and my company have picked over time, so it may not be the best fit for a super small project. For a more simple start, I suggest checking out `create-react-app` which was used to make [the simple example for react-redux-firebase](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/complete/simple).

**Comment by MincePie** [comment]
Thanks - I have a complex project and I am keen to try to use your setup for firebase. Just getting a bit confused with the ideas around multiple source folders etc. I am working on aggregating your folder content to try to fit within the application structure (moving root/src/actions for example, to the content created with the material example). I'm sure it's logical - I just can't figure it out yet. I'll keep trying for a couple more days before I give up - thanks again for sharing this. I'm sure there is something obvious that I just can't see yet.

**Comment by prescottprue** [comment]
Didn't realize that at first you were talking about the material example of react-redux-firebase. Once I realize, I went and looked and  I think that there is some unnecessary files there! The config folder is from an old setup of the generator before moving everything to `project.config.js`. You'll notice that [none of the examples in this repo contain that folder](https://github.com/prescottprue/generator-react-firebase/tree/master/examples).

Going to go remove those unnecessary files asap, I can see how that would be unclear.

If you have any other questions as you are checking things out, always feel free to reach out [over gitter](https://gitter.im/redux-firebase/Lobby).

**Comment by MincePie** [comment]
Also - fyi - I'm now getting a new error - apparently this plugin has been removed:

//   config.plugins.push(
//     new webpack.optimize.CommonsChunkPlugin({ names: bundles })
//   )


The suggestion is to use config.optimization.splitChunks instead

**Comment by prescottprue** [comment]
If you are looking for the most simple version that is similar to the output of create-react-app (uses `react-scripts`) , install from the `@next` tag. It will soon be released to latest.

Thanks for reaching out.
