### ISSUE TITLE
Firestore Security Rules not allowing to view /projects

### ISSUE THREAD

**Issue by costalvaro** [prescottprue/generator-react-firebase#142]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Installed generator today, started a project with Firestore.
Everything works correctly, I push it to Firebase (as the host).
Once rules are applied, I can no logger see project items when at /projects.
Console shows an error "Permission denied".

**What is the expected behavior?**
The projects should load correctly.

**Hint**
I played a little with the Firestore Rule Simulator, and found out that replacing the rule line
`allow read, write: if isOwner(request.resource);`
with
`allow read, write: if isOwner(resource);`
makes the trick, and access is correctly granted. 
Please verify this statement, and if required fix the existing rules generated.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Win10
node 9.11.1

(Thank you for this generator, that's a great help to start a project fastly!)

**Comment by costalvaro** [comment]
Additional input : With the hint I gave, showing & deleting existing projects was working.
However, creating projects was not possible anymore, so it wasn't a complete solution.

I have no clue about why it works that way, but then the complete solution so that everything works was the following : 
`allow read, write : if isOwner(resource) || isOwner(request.resource);`

- `isOwner(resource)` permits to get & delete
- `isOwner(request.resource)` permits to create

**Comment by prescottprue** [comment]
Fixed as part of [`v3.1.0` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v3.1.0), thanks for reporting.
