### ISSUE TITLE
missing documentation for deployment

### ISSUE THREAD

**Issue by jakobgn** [prescottprue/generator-react-firebase#145]
link to guide seem to be broken

**Comment by prescottprue** [comment]
Yeah, it looks like the info is only included in the [generated README](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/redux-firestore#ci-deploy-recommended), but the link in the main README assumes it is in that same file. Thanks for reaching out.

**Comment by prescottprue** [comment]
Copied it over to the main README. Feel free to reach out if anything else is unclear or if any other links are broken!
