### ISSUE TITLE
Compatibility react-redux@7

### ISSUE THREAD

**Issue by alanrivetta** [prescottprue/generator-react-firebase#154]
Hello, amazing boilerplate.

Could it be compatible with react-redux@7?

**Comment by prescottprue** [comment]
Updating past react-redux v6 requires switching to the newer version of react-redux-firebase and redux-firestore due to changing to the new/stable React context API, so it will take a bit of changing to make it work. That said, glad to folks are looking for this update so thanks for posting!

**Comment by LaurensLang** [comment]
I'm also interested in this.

**Comment by prescottprue** [comment]
[v4.0.0 release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v4.0.0) uses the newest react-redux (v7) and react-redux-firebase (v3). It also uses hooks in place of HOCs for data connection
