### ISSUE TITLE
bug(app): deleteProject does not remove project

### ISSUE THREAD

**Issue by mariotacke** [prescottprue/generator-react-firebase#166]
**Describe the bug**
`deleteProject` does not seem to remove the project. I just started using this generator and bootstrapped an application, set up configs, and ran the build without modifying any files. I also deployed via `firebase deploy` and made sure the database rules are configured and applied. I can create projects but the delete button does not trigger a network request to actually remove the project. The snack bar does show up and the `deleteProject` function completes without error. What am I missing?

**To Reproduce**
1. Generate new project with `yo react-firebase`
2. Run `npm start`
3. In web app, log in with Google or sign-up with email/password
4. Create a new project with any name
5. Click trash/delete icon on new project card
6. Notice snack bar showing project was removed but card still appears. Actual cloud firestore also still contains the project. No network request was made.

```js
// generated, not modified by me
function deleteProject() {
    return firebase
      .remove(`projects/${projectId}`)
      .then(() => showSuccess('Project deleted successfully'))
      .catch(err => {
        console.error('Error:', err) // eslint-disable-line no-console
        showError(err.message || 'Could not delete project')
        return Promise.reject(err)
      })
  }
```

**Environment**
- Babel version(s): latest generator versions
- Node/npm version: Node 8/npm 6
- OS: Windows 10
- Monorepo: no

**Comment by prescottprue** [comment]
@mariotacke Thanks for reaching out! It seems that is due to the fact that it is running delete within Real Time Database instead of Firestore. I'll look into fixing

**Comment by prescottprue** [comment]
Fixed in [v4.1.0 release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v4.1.0). Make sure to reinstall globally then rerun the generator in your project to get the update. Thanks for reporting!

**Comment by mariotacke** [comment]
@prescottprue thanks for the update. Unfortunately, now it just says "FirebaseError: Missing or insufficient permissions". I completely regenerated the project from scratch and redeployed everything. There are no source maps, so I can't pinpoint where this originates exactly. Interestingly, it throws two exceptions of the same type this time.

**Comment by prescottprue** [comment]
@mariotacke what do your Firestore rules look like? Did you deploy the included rules to your instance? Are you logged in? [This part of the included rules](https://github.com/prescottprue/generator-react-firebase/blob/master/generators/app/templates/firestore.rules#L23) should make it so that you can delete any project which was created by you.

**Comment by mariotacke** [comment]
@prescottprue, yes, I had deployed the rules and I am logged in (tried email auth/google auth, but made no difference).

I confirmed the projects get created in Cloud Firestore. When I hit delete (via the icon), it triggers 4 requests, all coming back as 200 and the triggering 2 `FirebaseError: Missing or insufficient permissions`.

These are my rules currently deployed for Cloud Firestore (they should be exactly the same):
```
service cloud.firestore {
  match /databases/{database}/documents {
    function isAuthed() {
      return request.auth.uid != null
    }
    function isOwner(res) {
      return res.data.createdBy == request.auth.uid
    }

    // Private user profiles
    match /users/{userId} {
      allow read;
      allow write: if request.auth.uid == userId;
    }

    // Public user profiles
    match /users_public/{userId} {
      allow read;
      allow write: if false; // only written to by indexUser cloud function
    }

    // Projects
    match /projects/{projectId} {
      // Only projects you own can be viewed
      allow create: if isOwner(request.resource);
      allow read, update: if isOwner(resource);
      // Rules apply to all child collections
      match /{allChildren=**} {
        allow read, write: if isOwner(get(/databases/$(database)/documents/projects/$(projectId)));
      }
    }
  }
}
``` 

And Realtime Database (even though that shouldn't matter):
```
{
  "rules": {
    ".read": "auth !== null",
    ".write":"auth !== null",
    "users": {
      "$uid": {
        ".write": "auth !== null && $uid === auth.uid"
      }
    },
    "projects": {
      ".indexOn": ["createdBy"]
    }
  }
}
```

The app is hosted here: https://influence-96d5c.firebaseapp.com/ (no changes from the template, just generated and deployed).

**Comment by mariotacke** [comment]
Is it missing the `delete` instruction?

Should it be:
```
match /projects/{projectId} {
  allow read, update, delete: if request.auth.uid == userId;
  allow create: if request.auth.uid != null;
}
```

?

**Comment by mariotacke** [comment]
That looks to be it. I changed the project section to (notice the `delete`):

```
match /projects/{projectId} {
 // Only projects you own can be viewed
 allow create: if isOwner(request.resource);
 allow read, update, delete: if isOwner(resource);
 // Rules apply to all child collections
 match /{allChildren=**} {
   allow read, write: if isOwner(get(/databases/$(database)/documents/projects/$(projectId)));
  }
}
```

**Comment by prescottprue** [comment]
Not sure why I didn't run into the same on my test instance. I'll make the changes to the outputted rules. Thanks for the detailed feedback!

**Comment by prescottprue** [comment]
Figured out why I didn't catch that - the rules in the test DB were still fully open due to testing another app. I'll make sure to keep those separate in the future. Thanks again

**Comment by mariotacke** [comment]
Thank you for the quick turn-around!
