### ISSUE TITLE
Module not found error after generator and npm run dev

### ISSUE THREAD

**Issue by darrenangle** [prescottprue/generator-react-firebase#17]
Ran the generator in an empty project folder, did npm install, and then npm run dev.

Getting this error: 

  app:bin:server Server is now running at http://192.168.1.8:3000. +10ms
  app:bin:server Server accessible via localhost:3000 if you are using the project defaults. +0ms
webpack built 5b9379db552922766ceb in 9499ms
Hash: 5b9379db552922766ceb
Version: webpack 1.13.2
Time: 9499ms
                                 Asset     Size  Chunks       Chunk Names
       app.5b9379db552922766ceb.js.map  2.56 MB       0       app
           app.5b9379db552922766ceb.js   2.1 MB       0       app
      2.Signup.5b9379db552922766ceb.js  69.8 kB       2       Signup
    3.Projects.5b9379db552922766ceb.js   152 kB       3       Projects
           4.4.5b9379db552922766ceb.js  1.13 kB       4       
     5.Project.5b9379db552922766ceb.js  18.9 kB       5       Project
     6.Account.5b9379db552922766ceb.js    78 kB       6       Account
        vendor.5b9379db552922766ceb.js   666 kB       7       vendor
       1.Login.5b9379db552922766ceb.js   115 kB       1       Login
   1.Login.5b9379db552922766ceb.js.map   138 kB       1       Login
  2.Signup.5b9379db552922766ceb.js.map  84.6 kB       2       Signup
3.Projects.5b9379db552922766ceb.js.map   181 kB       3       Projects
       4.4.5b9379db552922766ceb.js.map  1.44 kB       4       
 5.Project.5b9379db552922766ceb.js.map    23 kB       5       Project
 6.Account.5b9379db552922766ceb.js.map  94.7 kB       6       Account
    vendor.5b9379db552922766ceb.js.map   814 kB       7       vendor

ERROR in ./src/routes/Login/components/LoginForm/LoginForm.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../components/TextField in ...src/routes/Login/components/LoginForm
 @ ./src/routes/Login/components/LoginForm/LoginForm.js 24:17-57

ERROR in ./src/routes/Signup/components/SignupForm/SignupForm.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../components/TextField in ...src/routes/Signup/components/SignupForm
 @ ./src/routes/Signup/components/SignupForm/SignupForm.js 21:17-57
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  572 kB       0       
webpack: bundle is now VALID.

Any ideas?

**Comment by darrenangle** [comment]
Figured it out.

In both SignupForm.js and LoginForm.js the textfield import line should be: 
`import TextField from '../../../../components/TextField'`

instead of 
`import TextField from '../../../components/TextField'`

**Comment by prescottprue** [comment]
@darrenangle Great catch! Will make sure I fix this asap.

**Comment by prescottprue** [comment]
Fixed as part of [`v0.1.8` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v0.1.8).
