### ISSUE TITLE
Email doesn't appear on Account page

### ISSUE THREAD

**Issue by pshevtsov** [prescottprue/generator-react-firebase#195]
**Describe the bug**
After sign up and login, email doesn't appear on Account page.

**To Reproduce**

1. Generate app
1. Enable Email/Password sign-in method in Firebase Console
1. Signup using email and password
1. Go to /account
1. See empty text field for email

**Expected behavior/code**
Email appears on Account page

**Comment by prescottprue** [comment]
Which version are you running? 5.3.0? Want to make sure I am replicating with the correct form setup (switched to react-form-hook)

**Comment by prescottprue** [comment]
Thanks for reaching out! Fix released in [v5.3.1](https://github.com/prescottprue/generator-react-firebase/releases/tag/v5.3.1)
