### ISSUE TITLE
Login button is not enabled until the password field loses focus

### ISSUE THREAD

**Issue by pshevtsov** [prescottprue/generator-react-firebase#196]
**Describe the bug**
Login button is not enabled until the password field loses focus

**To Reproduce**

1. Go to /login
1. Fill username
1. Fill password
1. Login button is disabled

**Expected behavior/code**
Login button is enabled when all fields are valid.

**Additional Context/Screenshots**

![image](https://user-images.githubusercontent.com/290451/77284045-d3ca2000-6cde-11ea-83e8-39f8b230250a.png)

**Comment by prescottprue** [comment]
Thanks for reaching out! Fix released in [v5.3.1](https://github.com/prescottprue/generator-react-firebase/releases/tag/v5.3.1)
