### ISSUE TITLE
Error when setting up and starting dev server

### ISSUE THREAD

**Issue by henrylingumi** [prescottprue/generator-react-firebase#20]
When trying to start the dev server for the first time:

> ERROR in ./src/main.js
> Module build failed: Error: Couldn't find preset "react-server" relative to directory "/Users//Dropbox/Workspaces/FinalYearProject"
>     at /Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
>     at Array.map (native)
>     at OptionManager.resolvePresets (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
>     at OptionManager.mergePresets (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
>     at OptionManager.mergeOptions (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
>     at OptionManager.init (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
>     at File.initOptions (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/index.js:216:65)
>     at new File (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/file/index.js:139:24)
>     at Pipeline.transform (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
>     at transpile (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-loader/index.js:38:20)
>     at /Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-loader/lib/fs-cache.js:151:18
>     at ReadFileContext.callback (/Users//Dropbox/Workspaces/FinalYearProject/yo-react-generator-example/node_modules/babel-loader/lib/fs-cache.js:29:23)
>     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
>  @ multi app

**Comment by prescottprue** [comment]
Thanks for posting. Will look into this today.

**Comment by prescottprue** [comment]
Released [`v1.0.1`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.0.1) that might help. 

Let me know if you get a chance to try on your end. I will keep the issue open in the mean time.

**Comment by prescottprue** [comment]
@henrylingumi Are you still seeing this issue? If so is it possible for you to upload the output of the generator in a zip file or provide a link to a repo?

Currently I am not able to reproduce this error no matter what I do, but trying to make sure it is actually solved.

**Comment by prescottprue** [comment]
@henrylingumi Please try running `npm i -g generator-react-firebase` to update to the latest version, then try regenerating your project.
