### ISSUE TITLE
Issues creating project WITHOUT redux

### ISSUE THREAD

**Issue by mradenovic** [prescottprue/generator-react-firebase#211]
**Describe the bug**

* Firebase rules are not created
* Messaging is not initialized (different than when creating project with redux)
* Home Page throws an error
`FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument."`

**To Reproduce**
1. Create a project with `yo react-firebase`
2. Start the development with `npm start`

**Expected behavior/code**
* All firebase rules are created.
* Project works without errors.

**Possible Solution**

**Additional Context/Screenshots**

**.yo-rc.json** (only relevant fields included)

```json
{
  "generator-react-firebase": {
    "promptValues": {
      "githubUser": "mradenovic",
      "includeRedux": false,
      "includeFirestore": true,
      "otherFeatures": [
        "Continuous Integration config",
        "Firebase Cloud Messaging",
        "Firebase Functions (with ESNext support)",
        "Tests for Firebase Functions (Mocha/Chai or Jest)",
        "Firebase Analytics",
        "Segment.io Analytics",
        "Error Tracking (Sentry.io)",
        "Client Side Error Reporting (Stackdriver)"
      ],
      "functionsTestTool": "jest",
      "ciProvider": "githubActions",
      "deployTo": "firebase",
    }
  }
}

```

**Comment by prescottprue** [comment]
Same as the other issue - are you sure that you have Firebase fully setup for your project? Including setup of Firestore and RTDB?

**Comment by prescottprue** [comment]
Was it the appId issue here as well or are you having another issue with non-redux?

Messaging should be getting setup by [the SetupMessaging component in the App component](https://github.com/prescottprue/generator-react-firebase/blob/master/examples/react-firestore/src/containers/App/App.js#L28-L30). Are you finding that it isn't initialized?

**Comment by mradenovic** [comment]
Same as #212, The FirebaseError: was caused by a wrong appId on my side.

Firebase rules still not created, and I believe the messaging doesn't get initialized. I noticed that `initializeFirebase.js` file is not created and I'm not sure if it is by design.

**Comment by mradenovic** [comment]
Firebase rules are not created and this should probably go to another issue.

I figured out messaging, I had to setup `REACT_APP_FIREBASE_PUBLIC_VAPID_KEY` in `.env.local`. I was expecting it to work the same as redux version.

**Comment by prescottprue** [comment]
Oh yeah, that is part of the move I'm making towards using .env files for everything instead of needing the src/config.js. I'm going to switch that back to loading from src/config.js and do the env changes all at once - glad you caught that

The initializeFirebase file is only used when opting into redux.

**Comment by prescottprue** [comment]
@mradenovic Would you give updating v5.6.2 a try? I included fixes for the issues mentioned

**Comment by mradenovic** [comment]
Login throws an error. It looks like app is trying to access Projects, before getting the right s for it.

1. Sign Out
2. Sign In with Google (throws an error, see bellow)
3. Reload page, OK

```
Uncaught FirebaseError: Missing or insufficient permissions.

The above error occurred in the <ProjectsList> component:
    in ProjectsList (at ProjectsPage.js:23)
    in Suspense (created by SuspenseWithPerf)
    in SuspenseWithPerf (at ProjectsPage.js:20)
    in Route (at ProjectsPage.js:16)
    in Switch (at ProjectsPage.js:12)
    in ProjectsPage (at router.js:70)
    in Suspense (at router.js:69)
    in LoadableWrapper (created by Context.Consumer)
    in Route (at router.js:48)
    in AuthCheck (at router.js:38)
    in PrivateRoute (at routes/index.js:30)
    in Switch (at routes/index.js:18)
    in Suspense (created by SuspenseWithPerf)
    in SuspenseWithPerf (at routes/index.js:17)
    in div (at CoreLayout.js:10)
    in CoreLayout (at routes/index.js:16)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:27)
    in NotificationsProvider (at App.js:25)
    in FirebaseAppProvider (at App.js:24)
    in ThemeProvider (at App.js:23)
    in App (at src/index.js:21)

Consider adding an error boundary to your tree to customize error handling behavior.
```

**Comment by mradenovic** [comment]
This can be closed. The issue disappeared with `v5.7.0`.

**Comment by andreaherrera2316** [comment]
I got this issue when I deleted the "Browser key (auto created by Firebase)" in the google cloud console, so in order to solve I created a new firebase project and linked it to my existing app.
