### ISSUE TITLE
Issues creating project WITH redux

### ISSUE THREAD

**Issue by mradenovic** [prescottprue/generator-react-firebase#212]
**Describe the bug**

* It doesn't redirect after successful login.
* Projects page throws an error
`Uncaught TypeError: Cannot read property 'url' of undefined at src/utils/router.js`
* Home Page throws an error
`FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument."`

**To Reproduce**
1. Create a project with `yo react-firebase`
2. Start the development with `npm start`
3. Login
4. Go to Projects page

**Expected behavior/code**
* Project works without errors.
* Redirects after successful login.
* Project page can open.

**Possible Solution**

**Additional Context/Screenshots**

**.yo-rc.json** (only relevant fields included)

```json
{
  "generator-react-firebase": {
    "promptValues": {
      "githubUser": "mradenovic",
      "includeRedux": true,
      "includeFirestore": true,
      "otherFeatures": [
        "Continuous Integration config",
        "Firebase Cloud Messaging",
        "Firebase Functions (with ESNext support)",
        "Tests for Firebase Functions (Mocha/Chai or Jest)",
        "Firebase Analytics",
        "Segment.io Analytics",
        "Error Tracking (Sentry.io)",
        "Client Side Error Reporting (Stackdriver)"
      ],
      "functionsTestTool": "jest",
      "ciProvider": "githubActions",
      "deployTo": "firebase",
    }
  }
}

```

**Comment by prescottprue** [comment]
Hmm... The home page error seems to be that the project you are pointing to doesn't have a Firebase installation. Are you sure the project you are using is setup?

I'll look into trying to replicate the ProjectsPage issue

**Comment by mradenovic** [comment]
The `FirebaseError:` was caused by a wrong appId on my side.

A potential bug in `src/config.js` line 17 got my attention. The `measurementId` gets the value of `MessagingSenderId`. 

Redirect and Projects page still dont work.

**Comment by prescottprue** [comment]
v5.6.2 should fix the mentioned issues, thanks for the quick responses.

**Comment by mradenovic** [comment]
On Sign In with Google, flashes `Project Page` for a moment and then goes back to sign-in page and show notification `Error: Failed to get the document because the client is offline.`

After reload, opens `Project Page` with following console output:

This is probably the cause of the issue:
> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Redirect

This one doesn't have much sense since everything else works fine:
> [2020-05-01T02:33:28.945Z]  @firebase/firestore: Firestore (7.14.1): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
> This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Comment by prescottprue** [comment]
Lets open a new issue for that so tracking of debugging can go in there
