### ISSUE TITLE
Login buggy with redux and firebase@7.14.1

### ISSUE THREAD

**Issue by mradenovic** [prescottprue/generator-react-firebase#215]
**Describe the bug**

This is the copy of https://github.com/prescottprue/generator-react-firebase/issues/212#issuecomment-622222893 with possible solution.

On Sign In with Google, flashes Project Page for a moment and then goes back to sign-in page and show notification Error: Failed to get the document because the client is offline.

After reload, opens Project Page with following console output:

> [2020-05-01T02:33:28.945Z] @firebase/firestore: Firestore (7.14.1): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
> This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**To Reproduce**
1. Create a project with yo react-firebase
2. Start the development with npm start
3. Login
4. Go to Projects page

**Expected behavior/code**
* Project works without errors.
* Redirects after successful login.

**Possible Solution**
Downgrade to `firebase@7.13.1`.

This happened after update to `firebase@7.14.2`. It works well with `firebase@7.13.1`.
It might be firebase itself or one of the wrapper libraries.

**Comment by prescottprue** [comment]
@mradenovic I think it may be Firebase itself with that change, but I'll look into debugging further. Thanks for reporting!

As mentioned before, I think I'm going to switch the default to using non-redux

**Comment by prescottprue** [comment]
This was reported quite a while back and I was never able to reproduce. The generator now defaults to non redux and uses reactfire

Please reach out if you are still experiencing issues
