### ISSUE TITLE
TypeError: Cannot read property 'includeCI' of undefined

### ISSUE THREAD

**Issue by blackmad** [prescottprue/generator-react-firebase#226]
**Describe the bug**
Picking all the defaults results in a crash at the end with no files written out. I can repro this. It happens regardless of if I specify all my firebase creds.

version: 6.0.0
(base) ➜  pp2 yo react-firebase

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │   Welcome to the React   │
   `---------´   │    Firebase generator!   │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Github Username blackmad
? Include redux for local state-management? No
? Use Firestore (RTDB still included)? Yes
? Other Features To Include: Continuous Integration config, Firebase Cloud Messaging, Firebase Functions (with ESNext support), Tests for Firebase Functions (Mocha/Chai or
 Jest), Firebase Analytics, Error Tracking (Sentry.io), Client Side Error Reporting (Stackdriver)
? What tool would you like to use for testing cloud functions? Jest
? Firebase apiKey
? Firebase projectId (Firebase Console > Authentication > Web Setup) political-postcards
? Firebase Messaging Sender ID
? Firebase App Id
? Firebase Analytics Measurement ID (leave blank to skip)
? Sentry DSN (leave blank to skip)
? What provider which you like to use for CI? Github Actions
? Use Yarn? Yes
TypeError: Cannot read property 'includeCI' of undefined
    at module.exports.writing (/Users/blackmad/.nvm/versions/node/v13.6.0/lib/node_modules/generator-react-firebase/generators/app/index.js:311:22)
    at Object.<anonymous> (/Users/blackmad/.nvm/versions/node/v13.6.0/lib/node_modules/generator-react-firebase/node_modules/yeoman-generator/lib/index.js:893:25)
    at /Users/blackmad/.nvm/versions/node/v13.6.0/lib/node_modules/generator-react-firebase/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/blackmad/.nvm/versions/node/v13.6.0/lib/node_modules/generator-react-firebase/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/blackmad/.nvm/versions/node/v13.6.0/lib/node_modules/generator-react-firebase/node_modules/yeoman-generator/lib/index.js:894:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

**Comment by prescottprue** [comment]
Thanks for reporting, I will check into this

**Comment by w90** [comment]
I've got the same issue. I filled in all the fields manually, no defaults.

**Comment by prescottprue** [comment]
Thanks for reporting folks I'm going to remove this loading the github user code - having that load automatically doesn't warrant these major issues

**Comment by prescottprue** [comment]
@w90 and @blackmad could you both reinstall the latest and see if things are fixed for you? I removed the default github username logic which I believe was to blame (added in v6.0.0)
