### ISSUE TITLE
config.js not created

### ISSUE THREAD

**Issue by PeterLappo** [prescottprue/generator-react-firebase#234]
**Describe the bug**
config.js not created so compile fails 
./src/utils/analytics.js
Module not found: Can't resolve '../config' in '../react-firebase-prescottprue/src/utils'

Also a couple of typos?
* SetupAnalytics.js location changed to window
* initializeFirebase.js with a quote at the end
    messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID',

**To Reproduce**
yo --version
3.1.1
npm --version
6.14.4
node --version
v10.21.0
yarn --version
1.22.4
npm install -g yo generator-react-firebase 
as of 15 June 2020

yo react-firebase
with .yo-rc.json below
yarn start 

**Expected behavior/code**
Should start

**Possible Solution**

**Additional Context/Screenshots**
.yo-rc.json contains this

{
  "generator-react-firebase": {
    "promptValues": {
      "githubUser": "PeterLappo",
      "includeRedux": true,
      "includeFirestore": true,
      "otherFeatures": [
        "Continuous Integration config",
        "Firebase Cloud Messaging",
        "Firebase Functions (with ESNext support)",
        "Tests for Firebase Functions (Mocha/Chai or Jest)",
        "Tests for React Components (Jest)",
        "Firebase Analytics",
        "Error Tracking (Sentry.io)",
        "Client Side Error Reporting (Stackdriver)"
      ],
      "functionsTestTool": "jest",
      "firebaseKey": "my-key",
      "firebaseProjectId": "my-id",
      "messagingSenderId": "my-id",
      "appId": "my-appid",
      "measurementId": "",
      "firebasePublicVapidKey": "my-key",
      "ciProvider": "gitlab"
    }
  }
}

**Comment by prescottprue** [comment]
Thanks for reaching out, those do look like some issues! `src/config.js` was removed in favor of using environment variables, so looks like a reference was left behind.

Side note question though: What is your reasoning behind opting into redux? In v6.0.0 the generator was switched to defaulting to not using redux. Also interested in the choice of Gitlab over Github Actions

**Comment by prescottprue** [comment]
Ahh I was able to replicate what you are referencing - this appears to be from changes made to the non-redux version. Cleaning that up as well

**Comment by prescottprue** [comment]
[v6.1.1](https://github.com/prescottprue/generator-react-firebase/releases/tag/v6.1.1) was released with fixes for the issues you mentioned - let me know if you get a chance to try it out

**Comment by PeterLappo** [comment]
Just tried it and starts up without issues. 
Thanks

**Comment by PeterLappo** [comment]
> Side note question though: What is your reasoning behind opting into redux? In v6.0.0 the generator was switched to defaulting to not using redux. Also interested in the choice of Gitlab over Github Actions

Redux 
- was keeping my options open
Gitlab 
- using it at work 
- has free private repos with limitations 
- free build minutes 
- can be self hosted 
- test result integration is not great
- more CI rather than CD
Haven't used GitHub actions but suspect its less mature

**Comment by PeterLappo** [comment]
> Thanks for reaching out, those do look like some issues! `src/config.js` was removed in favor of using environment variables, so looks like a reference was left behind.

Not keen on environment variables they are a bit like secret globals but often necessary with docker. Ideally you just want one or two to select an environment.

Thanks again

**Comment by prescottprue** [comment]
@PeterLappo The usage of environment variables mirrors what is [outlined in the react-scripts docs](https://create-react-app.dev/docs/adding-custom-environment-variables/), but agree it might be nice to have a way to select settings based on a single variable - for that though, your configs would most likely want to be stored in the repo so they are tracked. This is actually what [the createConfig functionality of firebase-ci](https://github.com/prescottprue/firebase-ci#createconfig) was made for, but with that I have heard the input of "it is not good to modfiy/add files, which aren't tracked, as part of CI flow"

Guess it is just a case of pick your poison 😆  Either way, thanks for reporting the issues and giving input on reasons behind your decisions

**Comment by PeterLappo** [comment]
I like the .env idea with specific files for an environment as its explicit what environment variables there are. Others don't follow these conventions and expect environment variables to be set explicitly by the user leading to confusion.
