### ISSUE TITLE
Error: Cannot resolve module 'react/lib/EventPluginHub'

### ISSUE THREAD

**Issue by oriolsr** [prescottprue/generator-react-firebase#24]
```
ERROR in ./\~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in ./node_modules/react-tap-event-plugin/src
 @ ./\~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-37

ERROR in ./\~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in ./node_modules/react-tap-event-plugin/src
 @ ./\~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-56

ERROR in ./\~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginUtils' in ./node_modules/react-tap-event-plugin/src
 @ ./\~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-60

ERROR in ./\~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPropagators' in ./node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-60

ERROR in ./\~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/SyntheticUIEvent' in ./node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-60

ERROR in ./\~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in ./node_modules/react-tap-event-plugin/src
 @ ./\~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58
```

[material-ui#21](https://github.com/thereactivestack/meteor-webpack/issues/21)
[react-tap-event-plugin#82](https://github.com/zilverline/react-tap-event-plugin/pull/82)

Below dependencies should be updated
material-ui@0.16.3
react-tap-event-plugin@2.0.0

**Comment by oriolsr** [comment]
I've updated and fixed (defensively) both material-ui@16.0.3 and react-tap-event-plugin@2.0.0

Hope that helps!

**Comment by prescottprue** [comment]
Should be solved by [`v1.0.3` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.0.3). Going to open a separate issue for updating dependencies including getting material-ui to `v0.16.4` and tap-event-plugin to `v2.1.0`.

**Comment by MadeInMoon** [comment]
What worked for me:
- delete the `node_modules/` folder
- `npm install`

**Comment by prescottprue** [comment]
@MadeInMoon Yes, that should fix it in an already generated project. If you update using `npm i -g generator-react-firebase`, then future projects should be good from the start.

**Comment by washington-kibichii** [comment]
You are probably getting this error because you need to update a dependency in your project package.json file. In my case:
`"react-tap-event-plugin": "^1.0.0"` to `"react-tap-event-plugin": "^2.0.0"`
after making that change, remove the node_modules folder:
`rm -rf node_modules`

then finally:
`npm install`
