### ISSUE TITLE
Module not found error at project run

### ISSUE THREAD

**Issue by jd-alexander** [prescottprue/generator-react-firebase#282]
Hi, I ran this script and I am getting the error seen in the screenshot below no matter which configuration I utilize. 
<img width="1172" alt="Screenshot 2020-09-17 at 9 30 16 PM" src="https://user-images.githubusercontent.com/1509205/93548915-de800d80-f92d-11ea-8d41-fc736be0257c.png">

**Comment by prescottprue** [comment]
@jd-alexander It appears you are opting into redux - can you confirm so I can make sure I replicate correctly?

Also, out of curiosity, do you have a specific need for using redux from the start for your app?

**Comment by prescottprue** [comment]
I was able to replicate and it does appear that it was when opting into redux. The fix should be out shortly

**Comment by prescottprue** [comment]
v7.3.0 was released with a fix for this issue - please try running `npm i -g generator-react-firebase` to update. Please reach out if this doesn't fix the issue for you, thanks for reporting!

**Comment by jd-alexander** [comment]
Thanks for this quick fix @prescottprue I will give it a try.
