### ISSUE TITLE
Invalid.json generated when opting out of redux

### ISSUE THREAD

**Issue by Nateeo** [prescottprue/generator-react-firebase#29]
If the user answers 'No' to the 'Would you like to include redux for local state-management?' question, then the generator crashes when it tries to run `npm install`

This is due to a trailing comma on the last item (`react-tap-event-plugin": "1.0.0",`) in `dependencies` inside `package.json`

**Comment by prescottprue** [comment]
The PR fixing this is included in the [`v1.0.5` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.0.5).

Thanks!
