### ISSUE TITLE
can u provide the Firebase decorators docs...

### ISSUE THREAD

**Issue by CarreraPHP** [prescottprue/generator-react-firebase#35]
Hi prescottprue,

The decorator way of working with Firebase seems to be more comfortable way. Can you provide docs/api for the same. As this is very similar to the way i use to work with angular version2, I am finding it very easy to work with.

Btw, This is one of the Largest(LOC) generator i have used in recent times. It took me some time to under the flow of the application as i am new to React(not React Native) but later on, I realised all essential code needed for an web application are with the code generated.

Thanks for your effort.

Regards,
CarreraPHP

**Comment by prescottprue** [comment]
@CarreraPHP If you opt into using redux, decorators are used. See [the example with redux](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux).

[Here are some being used in the `ProjectContainer`](https://github.com/prescottprue/generator-react-firebase/blob/master/examples/react-firebase-redux/src/routes/Projects/containers/ProjectsContainer.js#L19-L35)

Yes, though the generator is large, it is meant to start from a place that can scale. Everything was added out of a need within a real life production work flow.

Glad you found it all essential! I have an article in the works about my experience within a team using all of this in production for multiple applications that might shed some more light on some of the obscure parts. It will be posted to the README as soon as it is available.

**Side Note:** Be sure to run `npm i -g generator-react-firebase` every now and then to get updates as they come in.
