### ISSUE TITLE
Compile error stack traces are missing source file name

### ISSUE THREAD

**Issue by Venryx** [prescottprue/generator-react-firebase#36]
When running "npm run dev" in a console, with code that causes a compile error, this is what is shown in the console:
![](http://i.imgur.com/YGzp4cB.png)

As can be seen, it doesn't say anywhere what source file has the issue!

My project was started from this template, and as far as I remember, this issue was present from the start. It's possible I configured something wrong -- though it was pretty straightforward, so I somewhat doubt that.

It's vexing to see a compile error and not know where to look!

**Comment by Venryx** [comment]
Okay, so I found the compile errors:
![](http://i.imgur.com/Gl1uIqC.png)

As shown, the _lines_ referenced in the compile error were correct, but just the filenames were missing for some reason.

**Comment by prescottprue** [comment]
Have you recently run `npm i -g generator-react-firebase` to update the generator?

If there is still an issue, I am working on `v1.2.0` that should fix any small file reference issues.

**Comment by Venryx** [comment]
Okay, I tried creating a new project using the generator (without updating it), and it correctly shows the stack traces of compile errors.

So apparently I did mess something up when I was configuring/setting-up my project.

I will investigate, but since it was probably just my fault somewhere, I guess I'll close the issue. (and if I find out what change caused it, I'll mention it here)

**Comment by Venryx** [comment]
I fixed it! Finally.

All I did was remove this line from the `webpack.config.js` file:
```diff
this.plugin("done", function (stats) {
	if (stats.compilation.errors.length) {
		// Log each of the warnings
		stats.compilation.errors.forEach(function (error) {
			errors.push(error.message || error)
		})

		// Pretend no assets were generated. This prevents the tests from running, making it clear that there were warnings.
-		throw new Error(errors)
	}
})
```

So I get that the above helps when running the tests, by just showing the compile errors instead of the would-be-confusing test-errors on top of that (I think). But I must have something set up wrong, because this occurs also for normal webpack-watch builds.

And this has been _terrible_.  Whenever I made even a tiny error, the entire webpack process (launched using `npm run dev`) would crash, requiring a full 1+ minute rebuild. Not only that; it also didn't display the stack-traces for any of the errors!

By removing the line above, errors finally show like they should (with stack-traces), and do _not_ cause the process to crash. Instead, it just waits for the next file-change so it can do another incremental compile. (as shown below -- *sighing in appreciation*)
![](http://i.imgur.com/iMTLY50.png)

Is this unintended behavior that only manifests in my project for some reason?

Or is it a template problem that could come up in other projects as well? (because if so, there should probably be a warning against it or something, and instructions on how to resolve it)

**Comment by Venryx** [comment]
Oh, looking at the code above, I just realized why it was showing the error messages but not the stack-traces. It's because of this code:
```diff
this.plugin("done", function (stats) {
	if (stats.compilation.errors.length) {
		// Log each of the warnings
+		stats.compilation.errors.forEach(function (error) {
+			errors.push(error.message || error)
+		})

		// Pretend no assets were generated. This prevents the tests from running, making it clear that there were warnings.
		throw new Error(errors)
	}
})
```

It should be this:
```diff
this.plugin("done", function (stats) {
	if (stats.compilation.errors.length) {
		// Log each of the warnings
		stats.compilation.errors.forEach(function (error) {
-			errors.push(error.message || error)
+			errors.push(error.stack || error.message || error)
		})

		// Pretend no assets were generated. This prevents the tests from running, making it clear that there were warnings.
		throw new Error(errors)
	}
})
```

So that would have helped, by at least making the errors more trackable.

However, having the process crash on syntax errors is the second (and more serious) issue. For the template, perhaps we could just have the "throw" line only execute when it's about to run tests.

**Comment by prescottprue** [comment]
[Release v1.2.2](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.2.2) has the changes that fix this.

Great catch, thanks for reporting!
