### ISSUE TITLE
Fails to compile out of the box

### ISSUE THREAD

**Issue by mikeover** [prescottprue/generator-react-firebase#369]
**Describe the bug**
Generated and ran `yarn start` and compile error occurs due to this issue: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21.

I updated the `extends` array in `.eslintrc.js` replacing `prettier` with `plugin:prettier/recommended` to get past this error.

However, next I ran `yarn start` again and am getting an error on `ProjectsList.jsx`:

```
src/routes/Projects/components/ProjectsList/ProjectsList.jsx
  Line 27:10:  Replace `⏎····data:·projects⏎··}·=·useFirestoreCollectionData(⏎····projectsRef,⏎···` with `·data:·projects·}·=·useFirestoreCollectionData(projectsRef,`  prettier/prettier
  Line 32:1:   Delete `··`                                                                                                                                              prettier/prettier
  Line 33:3:   Replace `··}⏎··` with `}`                                                                                                                                prettier/prettier
```

**To Reproduce**
1. Installed this generator and ran `yo react-firebase`
2. `yarn start`

**Expected behavior/code**
I expected it to work out of the box

**Comment by prescottprue** [comment]
Thanks for reporting! Did you opt to use redux or not? Not using redux is the default, but just wanted to confirm

**Comment by mikeover** [comment]
I opted out of redux.

**Comment by mikeover** [comment]
Out of curiosity, do you think you'll have a chance to address this in the near term? I'm starting a new project and would love to use this.

**Comment by prescottprue** [comment]
@mikeover Great question - I'm actually looking at it right now and it should hopefully be pretty easy to get something out today (famous last words)

**Comment by prescottprue** [comment]
Didn't notice the lint error you are referencing in ProjectsList, but was able to replicate the main error.

Went ahead and merged that so it should be released shortly, but wanted to call out that I also just started work on [v8.0.0](https://github.com/prescottprue/generator-react-firebase/pull/371) which will have a few nice updates like node 14 runtime (the only real planned breaking change is dropping old node versions)

If you are interested in trying, you can pull that v8.0.0 branch, npm linking generator-react-firebase, then generating. Also, if you want to wait, you can always regenerate in an existing project folder and opt in/out of changes to each file (I often do this and merge changes with my existing app code for whatever project)

**Comment by prescottprue** [comment]
Yup, here is [v7.6.3](https://github.com/prescottprue/generator-react-firebase/releases/tag/v7.6.3) - could you give that a try and confirm it works for you before we close this out?

**Comment by mikeover** [comment]
sure, trying now

**Comment by mikeover** [comment]
so if I just do a `yo react-firebase` (no redux, said no to all firebase things, yes to yarn), and then `yarn lint` gives me:
```
Error: "prettier/react" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
```

**Comment by mikeover** [comment]
I may have butchered that, I'm not very good with npm stuff. I tried updating the generator with `yo` and updating it, and re-ran it, now I'm getting an error:

```
ESLint couldn't find the plugin "eslint-plugin-prettier".

(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-prettier@latest --save-dev

The plugin "eslint-plugin-prettier" was referenced from the config file in ".eslintrc.js".
```

**Comment by mikeover** [comment]
and starting it, I still can't get past compiling ProjectsList:
```
Failed to compile.

src/routes/Projects/components/ProjectsList/ProjectsList.jsx
  Line 27:10:  Replace `⏎····data:·projects⏎··}·=·useFirestoreCollectionData(⏎····projectsRef,⏎···` with `·data:·projects·}·=·useFirestoreCollectionData(projectsRef,`  prettier/prettier
  Line 32:1:   Delete `··`                                                                                                                                              prettier/prettier
  Line 33:3:   Replace `··}⏎··` with `}`                                                                                                                                prettier/prettier

Search for the keywords to learn more about each error.
```

**Comment by prescottprue** [comment]
Did you reinstall the new version of the generator `npm i -g generator-react-firebase`

**Comment by prescottprue** [comment]
I just noticed that there was a typo in a package file setting which could cause the issues 🤦 

Having your answers will still be helpful so I can confirm

**Comment by mikeover** [comment]
I had tried updating within `yo` so trying now to reinstall via `npm`, and now getting this error on `yarn start`:
```
Failed to load plugin 'prettier' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /.../node_modules/react-scripts/config/__placeholder__.js
```

my `.yo-rc.json` is:
```
{
  "generator-react-firebase": {
    "promptValues": {
      "githubUser": "redacted",
      "includeRedux": false,
      "includeFirestore": true,
      "otherFeatures": [
        "Continuous Integration config",
        "Firebase Cloud Messaging",
        "Firebase Functions (with ESNext support)",
        "Tests for Firebase Functions (Mocha/Chai or Jest)",
        "Firebase Analytics",
        "Error Tracking (Sentry.io)",
        "Client Side Error Reporting (Stackdriver)"
      ],
      "functionsTestTool": "jest",
      "typescriptCloudFunctions": true,
      "firebaseKey": "redacted",
      "firebaseProjectId": "redacted",
      "messagingSenderId": "redacted",
      "appId": "redacted",
      "measurementId": "",
      "firebasePublicVapidKey": "redacted",
      "ciProvider": "githubActions"
    }
  }
}
```

**Comment by mikeover** [comment]
Just tried with new release v7.6.4. I got the same error but got to the next step by running `yarn add eslint-plugin-prettier`. 

But this gets me right back to the `prettier` errors when trying to `yarn start`:

```
src/routes/Projects/components/ProjectsList/ProjectsList.jsx
  Line 27:10:  Replace `⏎····data:·projects⏎··}·=·useFirestoreCollectionData(⏎····projectsRef,⏎···` with `·data:·projects·}·=·useFirestoreCollectionData(projectsRef,`  prettier/prettier
  Line 32:1:   Delete `··`                                                                                                                                              prettier/prettier
  Line 33:3:   Replace `··}⏎··` with `}`                                                                                                                                prettier/prettier

Search for the keywords to learn more about each error.
```

Would love to see this working, not sure if my comments are helping at all or not.

**Comment by mikeover** [comment]
FWIW I found that the `react-firebase` app in `examples` works for me AFTER I do `yarn add eslint-plugin-prettier` but it fails with the same above error message from prettier if I re-initialize and answer Y for `Use Firestore (RTDB still included)?`

**Comment by prescottprue** [comment]
That is so weird... wasn't able to replicate that myself and I was generating both the react-firebase and react-firestore examples then running 🤔 

There is also the react-firestore example which has firestore included

There has to be something going on here... I'll keep digging. Thanks for your patience - the reporting back definitely helps a bunch

**Comment by prescottprue** [comment]
Finally replicated! I was just checking the lint command, but start was picking up the issue you mentioned

**Comment by prescottprue** [comment]
[v7.6.5](https://github.com/prescottprue/generator-react-firebase/releases/tag/v7.6.5) was released with adding back that plugin and doing the formatting, so you should be good to go 🤞

**Comment by mikeover** [comment]
Great, thanks for your quick response and fix on this @prescottprue! I found another unrelated issue but I'll open a new thread.

**Comment by prescottprue** [comment]
Awesome 👏
