### ISSUE TITLE
Error with `tslib` when trying to `firebase deploy`

### ISSUE THREAD

**Issue by mikeover** [prescottprue/generator-react-firebase#382]
**Describe the bug**
I was not able to do `firebase deploy` because an error with the functions regarding `tslib`. I added `"tslib": "2.2.0"` to the dependencies in `functions/package.json` and then was able to deploy. Separate issue though

**To Reproduce**
Same steps as from https://github.com/prescottprue/generator-react-firebase/issues/369. I went through the manual deploy steps and once I got to `firebase deploy` it failed on deploying the functions until I added `tslib` to the package.json.

**Comment by prescottprue** [comment]
Also going through testing the fix in a full project which deploys through CI as well

**Comment by mikeover** [comment]
Cool I'm actually trying that now too, I haven't used TravisCI before so trying to figure out how to get it to trigger a build. Let me know if you stumble upon any gotchas or things that you do that aren't documented please!

**Comment by mikeover** [comment]
actually I'm not sure it's even setup right to run with Travis, seems the builds are all self-contained in Github actions (another thing I haven't used yet). some more documentation on how to setup CI would be helpful IMHO.

regardless, my github deploy is action is failing with:
`Invalid environment variable format 'REACT_APP_FB_projectId::my-app'`

**Comment by prescottprue** [comment]
If you haven't used a CI or have a strong preference I would highly suggest using Github Actions

Yeah seeing that myself as well - there was a change to Github Action's syntax for setting env variables working on addressing that now

**Comment by prescottprue** [comment]
Forgot to post, but released 7.6.6 with the fix for both the tslib and environment variable form: https://github.com/prescottprue/generator-react-firebase/releases/tag/v7.6.6

**Comment by mikeover** [comment]
this is working for you with github actions? I re-installed the generator, started from scratch with a new project, created the firebase token with `firebase-ci`, put it into my github secrets, and then ran the deploy action but still got `Invalid environment variable format 'REACT_APP_FB_projectId::my-app'`. am I doing something wrong?

**Comment by mikeover** [comment]
@prescottprue I opened a PR at https://github.com/prescottprue/generator-react-firebase/pull/384 to fix the env issue I'm seeing.

**Comment by prescottprue** [comment]
Didn't get a chance to test the full actions flow yesterday

Nope, you aren't doing anything wrong, I just never came back to fully update that Syntax after it changed on the Github Actions side. I'm going to do a bit more testing here to make sure the CI flows are working. Thanks again, super helpful!

**Comment by mikeover** [comment]
@prescottprue Any updates on the testing? With these changes the github action now succeeds for me but there is something wrong with the deploy itself as I end up with a blank page and `Uncaught (in promise) FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).` in the console.

**Comment by prescottprue** [comment]
Hey @mikeover I forgot to update, but i went through with the testing and didn't have an issue in a test project, [here is the successful deploy](https://github.com/prescottprue/firething/runs/2483077068?check_suite_focus=true).

What is the branch name for the build that was run? Do you have Did you check the CI logs to see which configs were loaded? This is dependent on matching aliases in `projects` within `.firebaserc`. The output in CI should look similar to the following (from [this build](https://github.com/prescottprue/firething/runs/2483077068?check_suite_focus=true#step:9:65)):
![image](https://user-images.githubusercontent.com/2992224/116789432-c0aa8780-aa7c-11eb-8d9b-212af2530ab7.png)
