### ISSUE TITLE
bug: Missing App configuration value: "projectId"

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/generator-react-firebase#391]
**Describe the bug**

`Uncaught (in promise) FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values)`
As [described here by @mikeover](https://github.com/prescottprue/generator-react-firebase/issues/382#issuecomment-827111702)

**To Reproduce**

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Possible Solution**

* Confirming settings in `.firebaserc` under `projects` matches branch structure (i.e. there is a project alias for the current branch such as `prod` for the `prod` branch)
**Additional Context/Screenshots**

**Comment by prescottprue** [comment]
[v8.0.0](https://github.com/prescottprue/generator-react-firebase/releases/tag/v8.0.0) was released with a bunch of major changes including how config is loaded in CI - @mikeover please reach out if you duplicate this issue with the new version

**Comment by mikeover** [comment]
@prescottprue Trying this today, initially my github deploy action is failing with:
```
i  functions: updating Node.js 14 (Beta) function indexUser(us-central1)...

Functions deploy had errors with the following functions:
	indexUser(us-central1)

To try redeploying those functions, run:
    firebase deploy --only "functions:indexUser"

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
✖ Error: Error in deploying to firebase:
 

 undefined
```

**Comment by prescottprue** [comment]
@mikeover Thanks for such a quick response! Thats weird... Were any messages writing to your functions logs in the console?

You should be able to add the following to your CI config to archive the log files that Firebase generates:

```yaml
# Archive build in case it needs to be downloaded later for debugging
- name: Archive Debug Logs
   if: ${{ failure() }}
   uses: actions/upload-artifact@v2
    with:
       name: debug-logs
       path: '*.log'
```

On that note, I'm going to add ^ to the deploy workflow in the generator for future debugging 🚀

**Comment by mikeover** [comment]
@prescottprue I'm not sure I understand your question but I added that step after the deploy but all it gave me was

```
Warning: No files were found with the provided path: *.log. No artifacts will be uploaded.
```

**Comment by mikeover** [comment]
Note also that trying to just deploy that function from the command line via `firebase deploy --only "functions:indexUser"` yields:
```
Error: package.json in functions directory has an engines field which is unsupported. The only valid choices are: {"node": "8"} and {"node": "10"}. Note that Node.js 6 is now deprecated.
```

**Comment by mikeover** [comment]
Fixed with this change and ready to roll:

```
diff --git a/functions/package.json b/functions/package.json
index cea7df3..be86c55 100644
--- a/functions/package.json
+++ b/functions/package.json
@@ -36,7 +36,7 @@
     "firebase-functions-test": "^0.2.3",
     "jest": "^26.6.3",
     "rimraf": "^3.0.2",
-    "ts-jest": "^26.4.2a",
+    "ts-jest": "^26.5.5",
     "ts-node": "^9.1.1",
     "typescript": "^4.2.4"
   }
```

**Comment by prescottprue** [comment]
The engines should be [set to 14.0.0 with v8.0.0 of the generator](https://github.com/prescottprue/generator-react-firebase/blob/master/generators/app/templates/functions/package.json#L7-L9) which matches what the newer versions of firebase-tools should, so not sure why that wouldn't be picked up correctly. Was this from your local machine or in CI? If it was from your local it could be due to an old version of firebase tools which is installed globally - firebase-tools is included as a dev dep too (which is used in CI), but you can use with `$(yarn bin)/firebase` or `$(npm bin)/firebase`

That dependency version issue issue is address in v8.0.1
