### ISSUE TITLE
Before starting is missing steps!

### ISSUE THREAD

**Issue by ulfsv** [prescottprue/generator-react-firebase#419]
I saw that the before starting is missing steps that are included in the local readme:

## Before Starting
1. Make sure you have `firebase-tools` installed an you are logged in (`firebase login`)
1. Create a project within the Firebase Console (or have one prepared to use)
1. Confirm billing is enabled for your project
1. Confirm [Firebase Hosting API](https://console.cloud.google.com/apis/library/firebasehosting.googleapis.com) is enabled for your project

Could be important for people who run this as their first Firebase project or have not installed the cli as was the case for me!

**Comment by prescottprue** [comment]
The main README was just covering what is needed for running the generating itself, but that said, want to make sure others aren't confused - I'll add. Thanks for calling out

**Comment by prescottprue** [comment]
Updated in v8.2.0, thanks for reporting!
