### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by udev** [prescottprue/generator-react-firebase#42]
I was able to successfully generate a project, build, run, and deploy yesterday.

Today I made a few changes and have been unable to successfully call `firebase serve` and render the site. I went as far as starting an entirely new project with the same result.

Upon calling `firebase serve` I get the following:

```
Server listening at: http://localhost:5000
127.0.0.1 - - [15/Apr/2017:05:51:42 +0000] "GET / HTTP/1.1" 200 417 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
127.0.0.1 - - [15/Apr/2017:05:51:42 +0000] "GET /favicon.ico HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```

but in the browser nothing is rendered and oddly enough the server seems to be looking for resources at port 3000

```
192.168.0.159:3000/vendor.f6c8d708fceb00e44a82.js Failed to load resource: net::ERR_CONNECTION_REFUSED
192.168.0.159:3000/app.f6c8d708fceb00e44a82.js Failed to load resource: net::ERR_CONNECTION_REFUSED
```

I've tried explicitly setting the listening port with `firebase serve -p 3000` but I get the same result.

**Comment by prescottprue** [comment]
Did you call `npm run build:prod` first? If you are doing `firebase serve` you will need to build all the static version (`dist` folder).

Port 3000 is if you run `npm start` which runs a live reloading & hot module reloading development server.

**Comment by udev** [comment]
Thanks. It ended up being a compound problem but I was definitely mixing up `npm start` and `firebase serve`. Additionally the error still occurs when attempting to use `npm start` in Chrome while [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en) is enabled so that was throwing me off. Definitely my fault for forgetting that I had that running. I'm able to hit the local site in an incognito window so all's well.

Thanks for the prompt reply! 👍
