### ISSUE TITLE
dependabot failing due to SERVICE_ACCOUNT missing

### ISSUE THREAD

**Issue by mikeover** [prescottprue/generator-react-firebase#427]
Dependabot fails with the following error:
`Throw a clear error if SERVICE_ACCOUNT secret is not set`

I've tried setting a `SERVICE_ACCOUNT` secret but I haven't figured it out yet.

**Comment by mikeover** [comment]
@prescottprue any thoughts on this? probably an easy fix that I can't seem to figure out.

**Comment by prescottprue** [comment]
@mikeover v8.2.0 includes separate workflows for dependabot which skip stages which require secrets - planning on trying to remove the requirement of secrets and a few more places, so that dependabot workflow should expand over time. Thanks for reporting!
