### ISSUE TITLE
react-router documentation links return 404

### ISSUE THREAD

**Issue by udev** [prescottprue/generator-react-firebase#44]
A couple of links to react-router documentation are broken

Under the [Routing](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux#routing) section: [route definitions](https://github.com/reactjs/react-router/blob/master/docs/API.md#plainroute)

And under [Static Deployments](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux#static-deployments): [this documentation](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#configuring-your-server)

**Comment by prescottprue** [comment]
Fix included in [`v1.2.3` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.2.3)
