### ISSUE TITLE
Fix "suspicious-website" in /examples/react-firebase-redux/README.md

### ISSUE THREAD

**Issue by emattson** [prescottprue/generator-react-firebase#48]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

`[Starting out with react-redux-starter-kit](https://suspicious.website/2016/04/29/starting-out-with-react-redux-starter-kit/)` Is a bad link

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Inspect link under the *Learning Resources* section in /examples/react-firebase-redux/README.md
Notice that it points to `https://suspicious.website/2016/04/29/starting-out-with-react-redux-starter-kit/`

**What is the expected behavior?**

Should probably point to a real and **safe** page. 

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Seems to have been there for a year or more based on git blame

**Comment by prescottprue** [comment]
Yeah, it seems that the whole README might need a bit of updating. I should be able to get to it soon.

**Comment by prescottprue** [comment]
@emattson [`v1.2.5`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.2.5) was released with this link removed. There are other enhancements in `v1.2.5` as well as other README simplifications.

Don't forget to run `npm i -g generator-react-firebase` to update the generator to the new version before running `yo react-firebase`.
