### ISSUE TITLE
NotFound does not export

### ISSUE THREAD

**Issue by morten-hogseth** [prescottprue/generator-react-firebase#56]
`NotFound.js`

Guess you guys forgot to export NotFound =)

export default NotFound

**Comment by prescottprue** [comment]
@morten-hogseth good catch, thanks for posting the issue. Making the fix now, and will release later today.

**Comment by prescottprue** [comment]
[`v1.4.1`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.4.1) was released with a fix for this.

Remember to run `npm i -g generator-react-firebase` to get the new version. Thanks for reporting!
