### ISSUE TITLE
Add index.js to components/containers for easier module referencing

### ISSUE THREAD

**Issue by davej** [prescottprue/generator-react-firebase#61]
For example:

```js
import Navbar from './Navbar'

export default Navbar
```

What do you think? Good idea or bad idea?

**Comment by prescottprue** [comment]
Isn't that [this file here?](https://github.com/prescottprue/generator-react-firebase/blob/master/examples/react-firebase-redux/src/containers/Navbar/index.js). Or am I missing something?

Was there a particular `index.js` missing?

**Comment by davej** [comment]
Sorry, should have been more clear. I mean when you run a sub-generator, i.e.. `yo react-firebase:component NavBar`

**Comment by prescottprue** [comment]
@davej Should be easy enough to add. Thanks for reporting!

**Comment by prescottprue** [comment]
@davej Added in [`v1.4.4`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.4.4).

Future issue -> solution time should hopefully be quicker, I have just been super busy with [`react-redux-firebase`](https://github.com/prescottprue/react-redux-firebase) recently.
