### ISSUE TITLE
Any change in redux store is re-rendering unaffected components.

### ISSUE THREAD

**Issue by phoenixrip** [prescottprue/generator-react-firebase#62]
*bug*?*

**What is the current behavior?**
I have a testCounter in my redux state. If I update the test counter every component that has been @firebaseconnected and then @connected will have a re-render triggered, even though none of them are @connected to the testCounter part of my redux state.

For Example:
In the following project build with this generator, a re-render will be triggered on every click of the counter link despite the counter not being required anywhere in the component:

my reducers.js file looks like this:

```
// ...dependencies

// TEST REDUCER
const testCounter = function (previousState = 0, action) {
  if (action.type === 'INC_TEST_COUNTER') {
    return previousState + 1
  }
  return previousState
}


export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    // Add sync reducers here
    firebase,
    testCounter,
    form,
    location: locationReducer,
    ...asyncReducers
  })
}
//...inject etc
```

And my component looks like this:
```
@firebaseConnect(({ params, auth }) => ([
  {
    path: 'projects'
  }
]))
@connect(
  ({ firebase }, { params }) => ({
    projects: dataToJS(firebase, 'projects'),
    auth: pathToJS(firebase, 'auth')
  }),
  (dispatch) => ({
    incTestCounter () {
      dispatch({
        type: 'INC_TEST_COUNTER'
      })
    }
  })
)
export default class Projects extends Component {
  render () {
    const { projects } = this.props

    if (!isLoaded(projects)) {
      return <LoadingSpinner />
    }

    console.log('Re-rendering even without being connected to the redux state thats changing')
    return (
      <div className={classes.container}>
        <p onTouchTap={this.props.incTestCounter}>INC RANDOM</p>
          {
            !isEmpty(projects) &&
               map(projects, (project, key) => (
                 <p key={key}>{project.title}</p>
              ))
          }
      </div>
    )
  }
}
```

**What is the expected behavior?**
I thought the expected behaviour was that if a component is not explicitly connected to that part of the redux state a re-render will not be triggered.
Obviously this can be worked around using shouldComponentUpdate but I just wanted to check that I wasn't doing something obviously wrong or that I've misunderstood a concept somewhere

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Brand new download and run of the generator, and every browser I've tried, chrome safari, firefox

**Comment by prescottprue** [comment]
@phoenixrip Unnecessary re-renders it an issue that has been tracked to be related to the fact that `v1.*.*` uses immutablejs.

As you mentioned, you can use shouldComponentUpdate to manage this, but if you don't want to have that logic, you may want to [check out the `v2.*.*` syntax of react-redux-firebase](http://docs.react-redux-firebase.com/history/v2.0.0/).

There will soon be a `v2.0.0` of this generator that generates projects with the react-redux-firebase v2 syntax.

**Comment by phoenixrip** [comment]
Thank you so much for a swift and concise response on this. I will certainly look into migrating over to react-redux-firebase 2.0.0 soon, love the idea of being able to persist the store as well.

**Comment by prescottprue** [comment]
@phoenixrip This seems it would fit more in the [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) repo, so I am going to close.

There has been large adoption of v2, so I definitely suggest going that route. As for things you can do for performance if you stick with v1:

* `dataToJS` does not need to be used in the connect function or at all for that matter - state in v1 is an Immutablejs object, so you can use its `get` and `set` methods instead of converting to a JS object
* Auth can be passed from higher components as a prop for more clear decorator setup

These points will soon be added to a performance section of the [react-redux-firebase docs](http://react-redux-firebase.com/)
