### ISSUE TITLE
"injectTapEventPlugin() must immediately precede ReactDOM.render()"

### ISSUE THREAD

**Issue by dfrho** [prescottprue/generator-react-firebase#64]
**Do you want to request a *feature* or report a *bug*?**  
Bug? - I'd be happy to generate the fix and pull request. Great work by the way, and thank you.

**What is the current behavior?**
I have the redux-generated option. On page load it throws console error from redbox library saying injectTapEventPlugin() must immediately precede ReactDOM.render(). This happened after I changed some material UI colors in the theme.js, which worked.

**What is the expected behavior?**
Page load without redbox error. I cleared the error message in console locally by following the instructions and moving  injectTapeventPlugin() to main.js Render Setup block, and importing at top of module of course. 

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Chrome 61.0.3*

**Comment by prescottprue** [comment]
@dfrho Great find! It would be awesome if you wanted to open a pull request, otherwise I will try to get to it this week.

**Comment by prescottprue** [comment]
[`v1.4.5`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.4.5) includes the fix for this. Thanks for reporting.
