### ISSUE TITLE
Upgrading generated package.json versions

### ISSUE THREAD

**Issue by russomi** [prescottprue/generator-react-firebase#8]
Hi @prescottprue - 

Thanks for getting this generator started -- I think this would be a benefit to the Firebase community since there doesn't seem to be a simple React + Firebase generator.  

There are a couple of items I would like to help out with:

- [x] Update versions for generated package.json to latest (especially Material-UI) ... this will require some rework in the generated markup.
- [x] Clean-up any unneeded packages - Are there any packages that are not needed in the generated package.json?  

Do you have any thoughts/guidance on how to proceed with these two items?  

Thanks!

**Comment by prescottprue** [comment]
@russomi I have updated Material-UI in another project that uses this generator, so I was about to copy that over to this. How about I create a branch and place that stuff on there so we can look at it together and compare?

As for unneeded packages, I have tried to eliminate all that are not needed, but let me know if you see any that you think can easily be removed.

I love the idea of making this generator community driven, so it will morph based on requests and suggested patterns. Much more to come from generator.

Side note: I just got v3 of Firebase working on my fork of [redux-react-firebase](https://github.com/prescottprue/redux-react-firebase), and am planning on implementing that (just waiting on PRs on the original repo).
