### ISSUE TITLE
feat(build): auto-chunk assets (such as routes)

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/generator-react-firebase#81]
Auto-chunk assets like routes using [`import` instead of `require.ensure`](https://webpack.js.org/guides/migrating/#code-splitting-with-es2015) (supported in Webpack 2)

Current Status:

* [X]  example of how to follow the pattern - @qalqi has provided [this example gist](https://gist.github.com/qalqi/ef4cbbc549631e64188266f0556be05f) of doing it with JSX routes
* [ ] research whether JSX or plain route objects should be used

**Comment by qalqi** [comment]
We can do that with JSX router similar to <Route path={ACCOUNT_PATH} getComponent={spinnerWhileAsyncRouteLoading(['importAccount'])}></Route>

**Comment by qalqi** [comment]
In case of nested routes with null object we can add specific error cases limited to that view with JSX routes... `<Route path={LIST_PATH} getComponent={importProjects}> <Route path=":projectname" getComponent={importProject}></Route> <Route path='*' exact={true} getComponent={importProjectNotFound}/> </Route>`

**Comment by qalqi** [comment]
Decoupling containers and routes will be useful with isomorphic react server side rendering

**Comment by prescottprue** [comment]
@qalqi Great input, and really love the idea of switching to `import` of `require.ensure`.

Still not sure I understand the advantage of using JSX over Plain route objects though. Both support what you are describing with specific error cases limited to certain views.

If we dive into the source of `react-router` we see that [the `Router` component actually just builds the plain route object instead of rendering](https://github.com/ReactTraining/react-router/blob/v3.0.0/modules/Router.js#L87). Not sure it matters either way, but it feels unnecessary to provide JSX which then gets converted back to plain objects anyway.

Also, as far as using the code splitting with server side rendering, I don't have too much experience, but [the `react-router` docs mention code splitting being pretty difficult when doing server-side rendering](https://reacttraining.com/react-router/web/guides/code-splitting/code-splitting-server-rendering)

**Comment by qalqi** [comment]
Here is an issue where plain js is biting https://github.com/ReactTraining/react-router/pull/3153

**Comment by prescottprue** [comment]
Just as a note, I was able to get child routes working like so:

```js
function errorLoading(err) {
  console.error('Dynamic page loading failed', err)
}

function loadRoute(cb) {
  return module => cb(null, module.default)
}

function loadChildRoutes(cb, store) {
  return modules => modules.forEach(module => module.default(store))
}

export default store => ({
  path: 'projects/:projectId',
  getComponent(nextState, cb) {
    import('./components/ProjectPage')
      .then(loadRoute(cb))
      .catch(errorLoading)
  },
  getChildRoutes(partialNextState, cb) {
    Promise.all([
      import('./routes/Child1'),
      import('./routes/Child2'),
      import('./routes/Child3')
    ])
      .then(loadChildRoutes(cb, store))
      .catch(errorLoading)
  }
})
```

Still planning to use JSX at the top level as you were saying, but figuring out child routes was holding me up.

**Comment by qalqi** [comment]
```
const importProjects = (nextState, cb) => {
  import (/* webpackChunkName: "projects" */
    'routes/Projects/containers/ProjectsContainer')
    .then(loadRoute(cb))
    .catch(errorLoading);
};

const importProject = (nextState, cb) => {
  import (/* webpackChunkName: "project" */
    'routes/Projects/routes/Project/containers/ProjectContainer')
    .then(loadRoute(cb))
    .catch(errorLoading);
};
    <Route path={LIST_PATH} getComponent={importProjects}>
      <Route path=":projectname" getComponent={importProject}></Route>
    </Route>

```
if you are using JSX there is no need for getChildRoutes

**Comment by prescottprue** [comment]
@qalqi I understand that with the JSX pattern, but I was looking for a way to have configuration still live within the route itself (allowing for easy movement between parent/child routes).

**Comment by qalqi** [comment]
@prescottprue Now that we are working this feature. Can we show a react reducer loading progress of webpack chunks in CoreLayout? Something similar to Github linear loading using 'material-ui/LinearProgress';

**Comment by qalqi** [comment]
A NPM library in these lines https://github.com/Storytel/react-redux-spinner

**Comment by prescottprue** [comment]
Work on this feature has started on the [v3.0.0-alpha brach](https://github.com/prescottprue/generator-react-firebase/tree/v3.0.0-alpha). The new setup is basically the same as ejecting from create-react-app (plus the original extras) and `react-loadable` for async routes.

**Comment by prescottprue** [comment]
This is available when installing from the `next` tag/branch.
