### ISSUE TITLE
SyntaxError: src/indexUser/index.js: Expecting Unicode escape sequence \uXXXX (48:51)

### ISSUE THREAD

**Issue by mylnz** [prescottprue/generator-react-firebase#88]
SyntaxError: src/indexUser/index.js: Expecting Unicode escape sequence \uXXXX (48:51)
  46 |
  47 |   const data = event.data.data()
> 48 |   const previousData = event.data.previous.data();\

remove the '\' character.

**Comment by prescottprue** [comment]
Fixed as part of [`v2.0.0-rc.6` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.0.0-rc.6). Reach out if it isn't working as expected. Thanks for reporting!
