### ISSUE TITLE
HomePage.js looks for Home.scss

### ISSUE THREAD

**Issue by flyingguitarman** [prescottprue/generator-react-firebase#90]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
updated generator this morning, started a new project without Material-UI, installed dependencies, ran npm start threw error. The SCSS file is still named Home.scss

**What is the expected behavior?**
It should be looking for HomePage.scss

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Windows 10.

**Comment by prescottprue** [comment]
@flyingguitarman Looks like the late night release last night was not the move! On the fix now, thanks for reporting.

**Comment by prescottprue** [comment]
Fixed as part of [`v2.0.0-rc.7` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.0.0-rc.7). Reach out if things aren't working as expected, thanks.
