### ISSUE TITLE
Generator throws an error while starting project

### ISSUE THREAD

**Issue by Panepo** [prescottprue/generator-react-firebase#92]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Installed generator today, started a project and an error occurred.

```
   create src\utils\errorHandler.js
   create src\utils\index.js
   create src\utils\analytics.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'message' of null
    at commandExists.then.then.catch (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\generator-react-firebase\generators\app\index.js:307:70)
    at <anonymous>
```

**What is the expected behavior?**
There should be no error?

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Win10 (Build 16299)
node 8.9.1

**Comment by prescottprue** [comment]
Thanks for reporting. Did you use yarn or npm?

It seems like we weren't getting an error message on something. Could you pull down the [`v2.0.0-rc.8` branch](https://github.com/prescottprue/generator-react-firebase/tree/v2.0.0-rc.8) and try npm linking (make sure they are the same node version)?

[This section of the react-redux-firebase docs](http://react-redux-firebase.com/docs/contributing.html#npm-linking) show how to do it with react-redux-firebase, but you would instead call `npm link generator-react-firebase` in the project.

With this we should be able to get better error logging.

**Comment by Panepo** [comment]
Thanks for replying. I use npm.

Another error occurred with the following commands:
```
git clone https://github.com/prescottprue/generator-react-firebase.git --branch  v2.0.0-rc.8 
cd generator-react-firebase
npm link
cd..
cd project
npm link generator-react-firebase
yo react-firebase
```
The error message is:
```
   create blueprints\route\index.js
   create src\utils\errorHandler.js
   create src\utils\index.js
   create src\utils\analytics.js
Error installing dependencies: null
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. (null)
    at module.exports.emit (events.js:186:19)
    at Immediate._onImmediate (D:\Github\generator-react-firebase\node_modules\yeoman-generator\lib\index.js:424:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
Is there anything I am doing wrong?
Thanks

**Comment by prescottprue** [comment]
The different error is "good" in the sense that it is somewhat helpful in debugging. Just a theory, but may potentially be the case of Yarn not existing may be handled a little differently on windows.

Pushed some changes to that same branch. Could you pull that same branch and repeat the linking steps.

Hoping that you see the log `"Yarn does not exist. Using NPM to install dependencies..."` then have the dependencies install. 

Thanks for help debugging, it is relatively time consuming to spin up VMs of different versions of windows to test things.

**Comment by prescottprue** [comment]
Just pushed changes up to the `v2.0.0-rc.8-install` branch that only offer yarn as an install option if it is available. Hopefully this fixes things in an even more graceful way.

Please let me know if you get a chance to try either/both.

**Comment by Panepo** [comment]
Just started two projects successfully with two respective branches linked: `v2.0.0-rc.8` and `v2.0.0-rc.8-install`

Thanks a lot.

**Comment by prescottprue** [comment]
Nice! Glad to hear, thanks for testing!

I'm going to go the route of merging the `v2.0.0-rc.8-install` branch (since it is a little more clean to only offer yarn if it exists).
